from machines import OsUpgradeStateMachine

sm = OsUpgradeStateMachine()
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")
print("Cycling to next state")
sm.send("cycle")
print(f"current state: {sm}")

